function newChessboardData() {
    return [
        { fieldNumber: 0, free: false, player: "black", figure: "black-rook" },
        { fieldNumber: 1, free: false, player: "black", figure: "black-knight" },
        { fieldNumber: 2, free: false, player: "black", figure: "black-bishop" },
        { fieldNumber: 3, free: false, player: "black", figure: "black-queen" },
        { fieldNumber: 4, free: false, player: "black", figure: "black-king" },
        { fieldNumber: 5, free: false, player: "black", figure: "black-bishop" },
        { fieldNumber: 6, free: false, player: "black", figure: "black-knight" },
        { fieldNumber: 7, free: false, player: "black", figure: "black-rook" },
        { fieldNumber: 8, free: false, player: "black", figure: "black-pawn" },
        { fieldNumber: 9, free: false, player: "black", figure: "black-pawn" },
        { fieldNumber: 10, free: false, player: "black", figure: "black-pawn" },
        { fieldNumber: 11, free: false, player: "black", figure: "black-pawn" },
        { fieldNumber: 12, free: false, player: "black", figure: "black-pawn" },
        { fieldNumber: 13, free: false, player: "black", figure: "black-pawn" },
        { fieldNumber: 14, free: false, player: "black", figure: "black-pawn" },
        { fieldNumber: 15, free: false, player: "black", figure: "black-pawn" },
        { fieldNumber: 16, free: true, player: null, figure: "" },
        { fieldNumber: 17, free: true, player: null, figure: "" },
        { fieldNumber: 18, free: true, player: null, figure: "" },
        { fieldNumber: 19, free: true, player: null, figure: "" },
        { fieldNumber: 20, free: true, player: null, figure: "" },
        { fieldNumber: 21, free: true, player: null, figure: "" },
        { fieldNumber: 22, free: true, player: null, figure: "" },
        { fieldNumber: 23, free: true, player: null, figure: "" },
        { fieldNumber: 24, free: true, player: null, figure: "" },
        { fieldNumber: 25, free: true, player: null, figure: "" },
        { fieldNumber: 26, free: true, player: null, figure: "" },
        { fieldNumber: 27, free: true, player: null, figure: "" },
        { fieldNumber: 28, free: true, player: null, figure: "" },
        { fieldNumber: 29, free: true, player: null, figure: "" },
        { fieldNumber: 30, free: true, player: null, figure: "" },
        { fieldNumber: 31, free: true, player: null, figure: "" },
        { fieldNumber: 32, free: true, player: null, figure: "" },
        { fieldNumber: 33, free: true, player: null, figure: "" },
        { fieldNumber: 34, free: true, player: null, figure: "" },
        { fieldNumber: 35, free: true, player: null, figure: "" },
        { fieldNumber: 36, free: true, player: null, figure: "" },
        { fieldNumber: 37, free: true, player: null, figure: "" },
        { fieldNumber: 38, free: true, player: null, figure: "" },
        { fieldNumber: 39, free: true, player: null, figure: "" },
        { fieldNumber: 40, free: true, player: null, figure: "" },
        { fieldNumber: 41, free: true, player: null, figure: "" },
        { fieldNumber: 42, free: true, player: null, figure: "" },
        { fieldNumber: 43, free: true, player: null, figure: "" },
        { fieldNumber: 44, free: true, player: null, figure: "" },
        { fieldNumber: 45, free: true, player: null, figure: "" },
        { fieldNumber: 46, free: true, player: null, figure: "" },
        { fieldNumber: 47, free: true, player: null, figure: "" },
        { fieldNumber: 48, free: false, player: "white", figure: "white-pawn" },
        { fieldNumber: 49, free: false, player: "white", figure: "white-pawn" },
        { fieldNumber: 50, free: false, player: "white", figure: "white-pawn" },
        { fieldNumber: 51, free: false, player: "white", figure: "white-pawn" },
        { fieldNumber: 52, free: false, player: "white", figure: "white-pawn" },
        { fieldNumber: 53, free: false, player: "white", figure: "white-pawn" },
        { fieldNumber: 54, free: false, player: "white", figure: "white-pawn" },
        { fieldNumber: 55, free: false, player: "white", figure: "white-pawn" },
        { fieldNumber: 56, free: false, player: "white", figure: "white-rook" },
        { fieldNumber: 57, free: false, player: "white", figure: "white-knight" },
        { fieldNumber: 58, free: false, player: "white", figure: "white-bishop" },
        { fieldNumber: 59, free: false, player: "white", figure: "white-queen" },
        { fieldNumber: 60, free: false, player: "white", figure: "white-king" },
        { fieldNumber: 61, free: false, player: "white", figure: "white-bishop" },
        { fieldNumber: 62, free: false, player: "white", figure: "white-knight" },
        { fieldNumber: 63, free: false, player: "white", figure: "white-rook" }
    ]
}


export default newChessboardData